PMTool/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMTool.EntityModel;

namespace PMTool.Controllers
{
    public class ActivitiesController : Controller
    {
        private PMTEntities2 db = new PMTEntities2();

        // GET: Activities
        public ActionResult Index()
        {
            var activities = db.Activities.Include(a => a.Task);
            return View(activities.ToList());
        }

        // GET: Activities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activities/Create
        public ActionResult Create()
        {
            ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name");
            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name");
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name");
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.Status = new SelectList(db.Status, "Name", "Name");
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name");
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.FK_DependentOn = new SelectList(db.Activities, "Id", "Name");
            ViewBag.AssignedTo = new SelectList(db.Employee365, "Id", "Name");

            return View();
        }

        // POST: Activities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FK_Task,Name,Description,StartDate,EndDate,ProjectOwner,Status,Budget,Progress,Priority,FK_Project,FK_Milestone,FK_MilestoneOwner,AssignedTo,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsActive,Longitude,Latitude,Radius,IsDependent,DependentOn,FK_ProjectOwner")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Activities.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name", activity.FK_Task);
            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name", activity.FK_Milestone);
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", activity.FK_Project);
  
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name", activity.FK_MilestoneOwner);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", activity.FK_ProjectOwner);


            return View(activity);
        }

        // GET: Activities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }

            ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name", activity.FK_Task);
            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name", activity.FK_Milestone);
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", activity.FK_Project);
     
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name", activity.FK_MilestoneOwner);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", activity.FK_ProjectOwner);
  

            return View(activity);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FK_Task,Name,Description,StartDate,EndDate,ProjectOwner,Status,Budget,Progress,Priority,FK_Project,FK_Milestone,FK_MilestoneOwner,AssignedTo,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsActive,Longitude,Latitude,Radius,IsDependent,DependentOn,FK_ProjectOwner")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name", activity.FK_Task);
            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name", activity.FK_Milestone);
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", activity.FK_Project);
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name", activity.FK_MilestoneOwner);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", activity.FK_ProjectOwner);
           


            return View(activity);
        }

        // GET: Activities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMTool/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PMTool.Controllers
{
    public class SharedController : Controller
    {
        

        public string[] SavePicture(HttpPostedFileWrapper[] pics)
        {
            string[] profilepath = new string[pics.Length];
            try
            {
                if (pics.Length > 0)
                {
                    for (int i = 0; i < pics.Length; i++)
                    {
                        string filename = System.IO.Path.GetRandomFileName().Replace(".", "") + pics[0].FileName;

                        pics[i].SaveAs(Server.MapPath("/ProjectFiles/" + filename));
                        profilepath[i] = "/ProjectFiles/" + filename;
                    }
                }
                return profilepath;

            }
            catch (Exception ex)
            {
                return profilepath;
            }

        }
    }
}

PMTool/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMTool.EntityModel;

namespace PMTool.Controllers
{
    public class TasksController : Controller
    {
        private PMTEntities2 db = new PMTEntities2();

        // GET: Tasks
        public ActionResult Index()
        {
            var tasks = db.Tasks.Include(t => t.MileStone);

            //ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name");
            //// ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name");
            //ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name");
            //ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name");
            //ViewBag.StatusT = new SelectList(db.Status, "Name", "Name");

            //ViewBag.Priority = new SelectList(db.Priorities.ToList(), "Name", "Name");
            //ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name");
            //ViewBag.FK_DependentOn = new SelectList(db.Tasks, "Id", "Name");
            //ViewBag.AssignedTo = new SelectList(db.Employee365, "Id", "Name");

            return View(tasks.ToList());
        }

        // GET: Tasks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name");
            ViewBag.FK_DependentTask = new SelectList(db.Tasks, "Id", "Name");
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name");
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.StatusT = new SelectList(db.Status, "Name", "Name");

            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name");
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.FK_DependentOn = new SelectList(db.Tasks, "Id", "Name");
            ViewBag.AssignedTo = new SelectList(db.Employee365, "Id", "Name");
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,StartDate,EndDate,ProjectOwner,Budget,Progress,FK_AssignTo,Status,Priority,FK_Project,FK_MileStone,FK_DependentTask,FK_MilestoneOwner,IsDependentTask,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsActive,Longitude,Latitude,Radius,IsApproved,ApprovedBy,ApprovedOn,FK_ProjectOwner")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name", task.FK_MileStone);
           // ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name", task.FK_Task);
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", task.FK_Project);
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name", task.FK_MilestoneOwner);
            ViewBag.AssignedTo = new SelectList(db.Employee365, "Id", "Name", task.FK_AssignTo);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", task.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", task.Status);
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", task.Priority);
            ViewBag.FK_DependentOn = new SelectList(db.Tasks, "Id", "Name", task.FK_DependentTask);

            return View(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name", task.FK_MileStone);
            // ViewBag.FK_Task = new SelectList(db.Tasks, "Id", "Name", task.FK_Task);
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", task.FK_Project);
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name", task.FK_MilestoneOwner);
            ViewBag.AssignedTo = new SelectList(db.Employee365, "Id", "Name", task.FK_AssignTo);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", task.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", task.Status);
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", task.Priority);
            ViewBag.FK_DependentOn = new SelectList(db.Tasks, "Id", "Name", task.FK_DependentTask);
            
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,StartDate,EndDate,ProjectOwner,Budget,Progress,FK_AssignTo,Status,Priority,FK_Project,FK_MileStone,FK_DependentTask,FK_MilestoneOwner,IsDependentTask,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsActive,Longitude,Latitude,Radius,IsApproved,ApprovedBy,ApprovedOn,FK_ProjectOwner")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_MileStone = new SelectList(db.MileStones, "Id", "Name", task.FK_MileStone);
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", task.FK_Project);
            ViewBag.AssignedTo = new SelectList(db.Employee365, "Id", "Name", task.FK_AssignTo);
            ViewBag.FK_MilestoneOwner = new SelectList(db.Employee365, "Id", "Name", task.FK_MilestoneOwner);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", task.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", task.Status);
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", task.Priority);
            ViewBag.FK_DependentOn = new SelectList(db.Tasks, "Id", "Name", task.FK_DependentTask);

            return View(task);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMTool/Views/Shared/_Footer.cshtml
<div class="row">
    <div class="col-lg-12">
        <div class="footer">
            <p>2018 © Admin Board. - <a href="#">example.com</a></p>
        </div>
    </div>
</div>

PMTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project Management Tool</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->

    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="@Url.Content("~/Content/assets/css/lib/calendar2/pignose.calendar.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/lib/chartist/chartist.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/lib/font-awesome.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/lib/themify-icons.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/lib/owl.carousel.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/assets/css/lib/owl.theme.default.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/assets/css/lib/weather-icons.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/assets/css/lib/menubar/sidebar.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/lib/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/lib/helper.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/assets/css/style.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/bootstrap-chosen.css")" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/image-uploader/dist/image-uploader.min.css">
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@

</head>
<body>
    <!-- /# sidebar -->
    @Html.Partial("~/Views/Shared/_Sidebar.cshtml");

    <!-- /# Header -->

    @Html.Partial("~/Views/Shared/_Header.cshtml");

    @RenderBody();
    <hr />

    @Html.Partial("~/Views/Shared/_Footer.cshtml");


    <!-- jquery vendor -->
    <script src="@Url.Content("~/Content/assets/js/lib/jquery.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/jquery.nanoscroller.min.js")"></script>
    <!-- nano scroller -->
    <script src="@Url.Content("~/Content/assets/js/lib/menubar/sidebar.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/preloader/pace.min.js")"></script>
    <!-- sidebar -->

    <script src="@Url.Content("~/Content/assets/js/lib/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/scripts.js")"></script>
    <!-- bootstrap -->

    <script src="@Url.Content("~/Content/assets/js/lib/calendar-2/moment.latest.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/calendar-2/pignose.calendar.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/calendar-2/pignose.init.js")"></script>


    <script src="@Url.Content("~/Content/assets/js/lib/weather/jquery.simpleWeather.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/weather/weather-init.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/circle-progress/circle-progress.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/circle-progress/circle-progress-init.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/chartist/chartist.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/sparklinechart/jquery.sparkline.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/sparklinechart/sparkline.init.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/owl-carousel/owl.carousel.min.js")"></script>
    <script src="@Url.Content("~/Content/assets/js/lib/owl-carousel/owl.carousel-init.js")"></script>
    <!-- scripit init-->
    <script src="@Url.Content("~/Scripts/chosen.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/chosen.jquery.min.js")"></script>
    <script type="text/javascript" src="~/Content/image-uploader/dist/image-uploader.min.js"></script>

    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @*@RenderSection("scripts", required: false)*@
</body>
</html>

PMTool/Views/Shared/_Sidebar.cshtml
<div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
    <div class="nano">
        <div class="nano-content">
            <ul>
                <div class="logo">
                    <a href="index.html">
                        <!-- <img src="Content/assets/images/logo.png" alt="" /> --><span>Focus</span>
                    </a>
                </div>
                <li class="label">Main</li>

                <li><a href="@Url.Action("Index","Home")"><i class="ti-home"></i>Dashboard</a></li>
                <li><a href="@Url.Action("Index","Projects")"><i class="ti-file"></i>Project</a></li>
                <li><a href="@Url.Action("Index","MileStones")"><i class="ti-file"></i>MileStone</a></li>
                <li><a href="@Url.Action("Index","Tasks")"><i class="ti-file"></i>Task</a></li>
                <li><a href="@Url.Action("Index","Activities")"><i class="ti-file"></i>Activity</a></li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-bar-chart-alt"></i> Charts <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="chart-flot.html">Flot</a></li>
                        <li><a href="chart-morris.html">Morris</a></li>
                        <li><a href="chartjs.html">Chartjs</a></li>
                        <li><a href="chartist.html">Chartist</a></li>
                        <li><a href="chart-peity.html">Peity</a></li>
                        <li><a href="chart-sparkline.html">Sparkle</a></li>
                        <li><a href="chart-knob.html">Knob</a></li>
                    </ul>
                </li>
                <li><a href="app-event-calender.html"><i class="ti-calendar"></i> Calender </a></li>
                <li><a href="app-email.html"><i class="ti-email"></i> Email</a></li>
                <li><a href="app-profile.html"><i class="ti-user"></i> Profile</a></li>
                <li><a href="app-widget-card.html"><i class="ti-layout-grid2-alt"></i> Widget</a></li>
                <li class="label">Features</li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-layout"></i> UI Elements <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="ui-typography.html">Typography</a></li>
                        <li><a href="ui-alerts.html">Alerts</a></li>

                        <li><a href="ui-button.html">Button</a></li>
                        <li><a href="ui-dropdown.html">Dropdown</a></li>

                        <li><a href="ui-list-group.html">List Group</a></li>

                        <li><a href="ui-progressbar.html">Progressbar</a></li>
                        <li><a href="ui-tab.html">Tab</a></li>

                    </ul>
                </li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-panel"></i> Components <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="uc-calendar.html">Calendar</a></li>
                        <li><a href="uc-carousel.html">Carousel</a></li>
                        <li><a href="uc-weather.html">Weather</a></li>
                        <li><a href="uc-datamap.html">Datamap</a></li>
                        <li><a href="uc-todo-list.html">To do</a></li>
                        <li><a href="uc-scrollable.html">Scrollable</a></li>
                        <li><a href="uc-sweetalert.html">Sweet Alert</a></li>
                        <li><a href="uc-toastr.html">Toastr</a></li>
                        <li><a href="uc-range-slider-basic.html">Basic Range Slider</a></li>
                        <li><a href="uc-range-slider-advance.html">Advance Range Slider</a></li>
                        <li><a href="uc-nestable.html">Nestable</a></li>

                        <li><a href="uc-rating-bar-rating.html">Bar Rating</a></li>
                        <li><a href="uc-rating-jRate.html">jRate</a></li>
                    </ul>
                </li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-layout-grid4-alt"></i> Table <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="table-basic.html">Basic</a></li>

                        <li><a href="table-export.html">Datatable Export</a></li>
                        <li><a href="table-row-select.html">Datatable Row Select</a></li>
                        <li><a href="table-jsgrid.html">Editable </a></li>
                    </ul>
                </li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-heart"></i> Icons <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="font-themify.html">Themify</a></li>
                    </ul>
                </li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-map"></i> Maps <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="gmaps.html">Basic</a></li>
                        <li><a href="vector-map.html">Vector Map</a></li>
                    </ul>
                </li>
                <li class="label">Form</li>
                <li><a href="form-basic.html"><i class="ti-view-list-alt"></i> Basic Form </a></li>
                <li class="label">Extra</li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-files"></i> Invoice <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="invoice.html">Basic</a></li>
                        <li><a href="invoice-editable.html">Editable</a></li>
                    </ul>
                </li>
                <li>
                    <a class="sidebar-sub-toggle">
                        <i class="ti-target"></i> Pages <span class="sidebar-collapse-icon ti-angle-down"></span>
                    </a>
                    <ul>
                        <li><a href="page-login.html">Login</a></li>
                        <li><a href="page-register.html">Register</a></li>
                        <li><a href="page-reset-password.html">Forgot password</a></li>
                    </ul>
                </li>
                <li><a href="../documentation/index.html"><i class="ti-file"></i> Documentation</a></li>
                <li><a><i class="ti-close"></i> Logout</a></li>
            </ul>
        </div>
    </div>
</div>