PMTool/Controllers/MileStonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMTool.EntityModel;

namespace PMTool.Controllers
{
    public class MileStonesController : Controller
    {
        private PMTEntities2 db = new PMTEntities2();

        // GET: MileStones
        public ActionResult Index()
        {
            var mileStones = db.MileStones;
            return View(mileStones.ToList());
        }

        // GET: MileStones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MileStone mileStone = db.MileStones.Find(id);
            if (mileStone == null)
            {
                return HttpNotFound();
            }
            return View(mileStone);
        }

        // GET: MileStones/Create
        public ActionResult Create()
        {
            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name");
            ViewBag.Status = new SelectList(db.Status, "Name", "Name");
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name");
            ViewBag.FK_DependentOn = new SelectList(db.MileStones, "Id", "Name");
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.CurrentlyAssignedTo = new SelectList(db.Employee365, "Id", "Name");
            
            return View();
        }

        // POST: MileStones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FK_Project,Name,Description,StartDate,EndDate,Status,Budget,Progress,Priority,FK_DependentOn,IsDependent,AssignedTo,IsActive,FK_ProjectOwner")] MileStone mileStone)
        {
            if (ModelState.IsValid)
            {
                db.MileStones.Add(mileStone);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", mileStone.FK_Project);
            ViewBag.CurrentlyAssignedTo = new SelectList(db.Employee365, "Id", "Name", mileStone.CurrentlyAssignedTo);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", mileStone.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", mileStone.Status);
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", mileStone.Priority);
            ViewBag.FK_DependentOn = new SelectList(db.MileStones, "Id", "Name",mileStone.FK_DependentOn);
            return View(mileStone);
        }

        // GET: MileStones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MileStone mileStone = db.MileStones.Find(id);
            if (mileStone == null)
            {
                return HttpNotFound();
            }

            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", mileStone.FK_Project);
            ViewBag.CurrentlyAssignedTo = new SelectList(db.Employee365, "Id", "Name", mileStone.CurrentlyAssignedTo);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name",mileStone.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", mileStone.Status);
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", mileStone.Priority);
            ViewBag.FK_DependentOn = new SelectList(db.MileStones, "Id", "Name", mileStone.FK_DependentOn);

            return View(mileStone);
        }

        // POST: MileStones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FK_Project,Name,Description,StartDate,EndDate,Status,Budget,Progress,Priority,FK_DependentOn,IsDependent,AssignedTo,IsActive,FK_ProjectOwner")] MileStone mileStone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mileStone).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_Project = new SelectList(db.Projects, "Id", "Name", mileStone.FK_Project);
            ViewBag.CurrentlyAssignedTo = new SelectList(db.Employee365, "Id", "Name", mileStone.CurrentlyAssignedTo);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name",mileStone.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", mileStone.Status);
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", mileStone.Priority);
            ViewBag.FK_DependentOn = new SelectList(db.MileStones, "Id", "Name", mileStone.FK_DependentOn);

            return View(mileStone);
        }

        // GET: MileStones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MileStone mileStone = db.MileStones.Find(id);
            if (mileStone == null)
            {
                return HttpNotFound();
            }
            return View(mileStone);
        }

        // POST: MileStones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MileStone mileStone = db.MileStones.Find(id);
            db.MileStones.Remove(mileStone);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMTool/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using PMTool.EntityModel;

namespace PMTool.Controllers
{
    public class ProjectsController : SharedController
    {
        private PMTEntities2 db = new PMTEntities2();

        // GET: Projects
        public ActionResult Index()
        {
            var projects = db.Projects;
            return View(projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            Project project = new Project();
            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name");
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.employee365s = new SelectList(db.Employee365, "Id", "Name");
           
            ViewBag.Status = new SelectList(db.Status, "Name", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,UploadAttachement,StartDate,EndDate,Status,FK_ProjectOwner,Budget,Progress,Priority,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsActive,employee365s,images,files")] Project project)
        {
            if (ModelState.IsValid)
            {
                List<Attachment> Attachmentss = new List<Attachment>();
                foreach (HttpPostedFileBase file in project.files)
                {
                    //Checking file is available to save.  
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/ProjectFiles/") + InputFileName);
                        //Save file to server folder  
                        file.SaveAs(ServerSavePath);
                       
                        //assigning file uploaded status to ViewBag for showing message to user.  
                        //ViewBag.UploadStatus = project.files.Count().ToString() + " files uploaded successfully.";

                        //project.ProductPictureList = new List<Attachment>();
                        
                            Attachment objprflepicpth = new Attachment();
                            objprflepicpth.Path = ServerSavePath;


                            var full = InputFileName.Split('.');

                            var fullLength = 1;
                            for (int j = full.Length - 1; j >= 0; j--)
                            {
                                fullLength = full.Length - 1;
                                if (fullLength == j)
                                {
                                    objprflepicpth.extention = full[j].ToString();
                                }
                                else
                                {
                                    objprflepicpth.Name += full[j].ToString();
                                }
                            }
                        Attachmentss.Add(objprflepicpth);
                    }

                }

                //Procedure Working
                //int proId = 0;
                ObjectParameter exceptionMessage = new ObjectParameter("ExceptionMessage", typeof(string));
                ObjectParameter validateMessage = new ObjectParameter("ValidateMessage", typeof(string));
                ObjectParameter proId = new ObjectParameter("ProId", typeof(int));

                var res = db.SP_AddProject(project.Name, project.Description, project.UploadAttachement, project.StartDate, project.EndDate,
                             project.FK_ProjectOwner, project.Status, project.Budget, project.Progress, project.Priority, null, null, project.CreatedBy, null, project.ModifiedBy,
                             project.IsActive, exceptionMessage,validateMessage,proId);

                List<int> empIds=  project.employee365s.ToList();
                for(int i=0; i < project.employee365s.Count(); i++)
                {
                    var ProId = proId.Value;
                    var empId = empIds[i];
                    var empName = db.Employee365.Where(x => x.Id == empId).Select(m => m.Name).FirstOrDefault();

                    var result = db.AddProjectMember(empName, (int?)ProId,empId,null, project.CreatedBy, null, project.ModifiedBy,
                             project.IsActive, exceptionMessage, validateMessage);
                }

                if (Attachmentss != null)
                {
                    foreach (var item in Attachmentss)
                    {

                        var result = db.AddAttachment(item.Name,item.Path,item.extention, (int?)proId.Value, null, project.CreatedBy, null, project.ModifiedBy,
                            project.IsActive, exceptionMessage, validateMessage);
                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", project.Priority);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", project.FK_ProjectOwner);
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", project.Status);
            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            //Attachment attachment = db.Attachments.FirstOrDefault(a => a.FK_Project == id);
            //project.UploadAttachement = attachment.Name;

            if (project == null)
            {
                return HttpNotFound();
            }

            ViewBag.Priority = new SelectList(db.Priorities, "Name", "Name", project.Priority);
            ViewBag.FK_ProjectOwner = new SelectList(db.Employee365, "Id", "Name", project.FK_ProjectOwner);
            ViewBag.employee365s = new SelectList(db.Employee365, "Id", "Name");
            ViewBag.Status = new SelectList(db.Status, "Name", "Name", project.Status);

            List<ProjectMember> pms = new List<ProjectMember>();
            var projectmembers = db.ProjectMembers.Where(x => x.FK_Project == id).ToList();
            for(int i=0; i < projectmembers.Count(); i++)
            {
                ProjectMember projectMember = new ProjectMember();
                projectMember.Id = (int)projectmembers[i].FK_Employee365ID;
                projectMember.Name = projectmembers[i].Name;
                pms.Add(projectMember);
            }
            ViewBag.employees = pms;

            List<Attachment> attachments = new List<Attachment>();
            var ProAttachments = db.Attachments.Where(x => x.FK_Project == id).ToList();
            for (int i = 0; i < ProAttachments.Count(); i++)
            {
                Attachment attachment = new Attachment();
                attachment.Name = ProAttachments[i].Name;
                // Id On delete button
                attachment.Id = ProAttachments[i].Id;
                attachments.Add(attachment);
            }
            project.ProductPictureList = attachments;
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,UploadAttachement,StartDate,EndDate,FK_ProjectOwner,Status,Budget,Progress,Priority,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsActive,employee365s,files")] Project project)
        {
            if (ModelState.IsValid)
            {
                List<Attachment> Attachmentss = new List<Attachment>();
                foreach (HttpPostedFileBase file in project.files)
                {
                    //Checking file is available to save.  
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/ProjectFiles/") + InputFileName);
                        //Save file to server folder  
                        file.SaveAs(ServerSavePath);

                        //assigning file uploaded status to ViewBag for showing message to user.  
                        //ViewBag.UploadStatus = project.files.Count().ToString() + " files uploaded successfully.";

                        //project.ProductPictureList = new List<Attachment>();

                        Attachment objprflepicpth = new Attachment();
                        objprflepicpth.Path = ServerSavePath;


                        var full = InputFileName.Split('.');

                        var fullLength = 1;
                        for (int j = full.Length - 1; j >= 0; j--)
                        {
                            fullLength = full.Length - 1;

PMTool/Views/MileStones/Delete.cshtml
@model PMTool.EntityModel.MileStone

@{
    ViewBag.Title = "Delete";
}

<div class="content-wrap">
    <div class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 p-r-0 title-margin-right">
                    <div class="page-header">
                        <div class="page-title">

                        </div>
                    </div>
                </div>

                <div class="col-lg-4 p-l-0 title-margin-left">
                    <div class="page-header">
                        <div class="page-title">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active">Milestone</li>
                            </ol>
                        </div>
                    </div>
                </div>

            </div>

            <section id="main-content">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
                    </div>
                }
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    <h4>MileStone</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.StartDate)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.StartDate)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.EndDate)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EndDate)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Status)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Status)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Budget)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Budget)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Progress)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Progress)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Priority)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Priority)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FK_DependentOn)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FK_DependentOn)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.IsDependent)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.IsDependent)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.AssignedTo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AssignedTo)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FK_ProjectOwner)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FK_ProjectOwner)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Project.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Project.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.IsActive)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.IsActive)
                        </dd>


                    </dl>


                </div>
            </section>
        </div>
    </div>
</div>

PMTool/Views/MileStones/Index.cshtml
@model IEnumerable<PMTool.EntityModel.MileStone>

@{
    ViewBag.Title = "Index";
}

@{
    int rowNo = 1;
}
<div class="content-wrap">
    <div class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 p-r-0 title-margin-right">
                    <div class="page-header">
                        <div class="page-title">

                        </div>
                    </div>
                </div>

                <div class="col-lg-4 p-l-0 title-margin-left">
                    <div class="page-header">
                        <div class="page-title">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Dashboard</a></li>
                                <li class="breadcrumb-item active"><a href="@Url.Action("Index","Projects")"> Project</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <h4> Milestone List</h4>
                @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })
                <div class="grid">

                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>S#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>

                                    <th>Budget</th>
                                    <th>Progress</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                    <th>Action</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td scope="row">@rowNo</td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.StartDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EndDate)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Budget)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Progress)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Priority)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Status)
                                    </td>
   
                        
    
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IsActive)
                                    </td>

                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new
                                   {
                                       @class = "badge badge-primary"
                                   })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new
                                   {
                                       @class = "badge badge-info"
                                   })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new
                                   {
                                       @class = "badge badge-danger"
                                   })
                                    </td>
                                </tr>
                                    rowNo = rowNo + 1;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>